#lang info
(define collection "keccak256")
(define deps '("base"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
(define scribblings '(("scribblings/keccak256.scrbl" ())))
(define pkg-desc "Description Here")
(define version "0.0")
(define pkg-authors '(bkc))
(define license '(Apache-2.0 OR MIT))
(define pre-install-collection "private/install-XKCP-keccak-compact.rkt")
