#lang info
(define collection "keccak")
(define deps '("base" "dynext-lib" "openssl"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
(define scribblings '(("scribblings/keccak.scrbl" ())))
(define pkg-desc "Keccak cryptographic hash algorithm.")
(define version "0.1")
(define pkg-authors '(bkc))
(define license '(Apache-2.0 OR MIT))
(define pre-install-collection "private/install-XKCP-keccak-compact.rkt")
